language: python

cache: pip

python:
  - "3.8"

install:
  - pip install poetry codecov
  - poetry install
  - cp .env .env

script:
  - make test lint
  - python setup_.py build

branches:
  only:
    - develop
